ALTER SESSION SET CURRENT_SCHEMA=CHP
/

DROP TABLE CHP.TB_M_UNIVERSAL_FIELD_TEMP;
CREATE TABLE CHP.TB_M_UNIVERSAL_FIELD_TEMP
(
    UNIVERSAL_FIELD_CODE       VARCHAR2(100 char)       not null
        constraint PK_UNIVERSAL_FIELD_TEMP
            primary key,
    UNIVERSAL_FIELD_NAME   VARCHAR2(500 char),
    UNIVERSAL_FIELD_TYPE   VARCHAR2(100 char),
    IS_ACTIVE     CHAR(1 char) not null,
    CREATE_DATE   TIMESTAMP(6) not null,
    CREATE_USER   VARCHAR2(50 char),
    UPDATE_DATE   TIMESTAMP(6),
    UPDATE_USER   VARCHAR2(50 char)
)
    LOGGING
    TABLESPACE CHPMASDATATBS
    PCTFREE 10
    INITRANS 1
    STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
) NOCOMPRESS;



CREATE UNIQUE INDEX CHP.PK_UNIVERSAL_FIELD_TEMP ON CHP.TB_M_UNIVERSAL_FIELD_TEMP (UNIVERSAL_FIELD_CODE ASC)
    LOGGING
    TABLESPACE CHPMASDATATBS
    PCTFREE 10
    INITRANS 2
    STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOPARALLEL;

GRANT SELECT, INSERT, UPDATE, DELETE ON CHP.TB_M_UNIVERSAL_FIELD_TEMP to DBCHP;
COMMIT;

